# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 651)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rcs/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setWhatsThis("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 290))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 251, 255))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_onConnect = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_onConnect.setCheckable(False)
        self.pushButton_onConnect.setAutoDefault(False)
        self.pushButton_onConnect.setDefault(False)
        self.pushButton_onConnect.setFlat(False)
        self.pushButton_onConnect.setObjectName("pushButton_onConnect")
        self.gridLayout.addWidget(self.pushButton_onConnect, 5, 0, 1, 2)
        self.lineEdit_database = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_database.setObjectName("lineEdit_database")
        self.gridLayout.addWidget(self.lineEdit_database, 4, 1, 1, 1)
        self.pushButton_getList = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_getList.setObjectName("pushButton_getList")
        self.gridLayout.addWidget(self.pushButton_getList, 6, 0, 1, 2)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ip.setPlaceholderText("")
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.gridLayout.addWidget(self.lineEdit_ip, 0, 1, 1, 1)
        self.lineEdit_hostDB = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_hostDB.setObjectName("lineEdit_hostDB")
        self.gridLayout.addWidget(self.lineEdit_hostDB, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_userDB = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_userDB.setObjectName("lineEdit_userDB")
        self.gridLayout.addWidget(self.lineEdit_userDB, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_passwdDB = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_passwdDB.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_passwdDB.setObjectName("lineEdit_passwdDB")
        self.gridLayout.addWidget(self.lineEdit_passwdDB, 3, 1, 1, 1)
        self.comboBox_listMachines = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_listMachines.setObjectName("comboBox_listMachines")
        self.gridLayout.addWidget(self.comboBox_listMachines, 7, 1, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout.addWidget(self.pushButton_run, 7, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 291, 290))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 30, 251, 251))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(320, 10, 571, 581))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_listMachines = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_listMachines.setEnabled(True)
        self.tableWidget_listMachines.setGeometry(QtCore.QRect(0, 5, 561, 511))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tableWidget_listMachines.setFont(font)
        self.tableWidget_listMachines.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_listMachines.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_listMachines.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_listMachines.setShowGrid(True)
        self.tableWidget_listMachines.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_listMachines.setWordWrap(True)
        self.tableWidget_listMachines.setRowCount(100)
        self.tableWidget_listMachines.setObjectName("tableWidget_listMachines")
        self.tableWidget_listMachines.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listMachines.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listMachines.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listMachines.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listMachines.setHorizontalHeaderItem(3, item)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(360, 520, 201, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_setTimeOff = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_setTimeOff.setMaxLength(30000)
        self.lineEdit_setTimeOff.setFrame(True)
        self.lineEdit_setTimeOff.setObjectName("lineEdit_setTimeOff")
        self.horizontalLayout.addWidget(self.lineEdit_setTimeOff)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 0, 570, 555))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PB2 PiR"))
        MainWindow.setStatusTip(_translate("MainWindow", "itada1997"))
        self.groupBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Step 1: Connect to Database</p><p>Step 2: Get Machines List</p><p>Step 3: Choose group</p><p>Step 4: Run</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "FIRST STEP"))
        self.pushButton_onConnect.setText(_translate("MainWindow", "Connect to Database"))
        self.lineEdit_database.setText(_translate("MainWindow", "pj_hbi"))
        self.pushButton_getList.setText(_translate("MainWindow", "Get Machines List"))
        self.lineEdit_ip.setText(_translate("MainWindow", "192.168.0.108"))
        self.lineEdit_hostDB.setText(_translate("MainWindow", "localhost"))
        self.label_4.setText(_translate("MainWindow", "Passwd"))
        self.label_3.setText(_translate("MainWindow", "User DB"))
        self.lineEdit_userDB.setText(_translate("MainWindow", "root"))
        self.label_5.setText(_translate("MainWindow", "Database"))
        self.label_2.setText(_translate("MainWindow", "Host DB"))
        self.label.setText(_translate("MainWindow", "IP Server"))
        self.lineEdit_passwdDB.setText(_translate("MainWindow", "tuan123"))
        self.pushButton_run.setText(_translate("MainWindow", "RUN"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ON CONNECT STATUS"))
        self.tableWidget_listMachines.setSortingEnabled(False)
        item = self.tableWidget_listMachines.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MecID"))
        item = self.tableWidget_listMachines.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LINE"))
        item = self.tableWidget_listMachines.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Qty"))
        item = self.tableWidget_listMachines.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ON/OFF"))
        self.label_6.setText(_translate("MainWindow", "Time OFF( in minutes)"))
        self.lineEdit_setTimeOff.setText(_translate("MainWindow", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "List Machines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Processing"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
